services:
  grafana-alloy:
    image: grafana/alloy:latest
    volumes:
      - ./alloy-config.yaml:/etc/alloy/config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8889:8889"  # Prometheus metrics endpoint
    restart: unless-stopped
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    restart: unless-stopped
    networks:
      - observability
    depends_on:
      - loki
      - prometheus
      - tempo

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - observability

  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo/tempo-local.yaml
    volumes:
      - ./tempo-config.yaml:/etc/tempo/tempo-local.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200"  # tempo
    restart: unless-stopped
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - observability

networks:
  observability:

volumes:
  grafana-storage:
  loki-data:
  tempo-data:
  prometheus-data: