services:
  grafana-alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command: ["run", "/etc/alloy/config.alloy"]
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy:ro
    ports:
      # Only map these if receiving OTLP from OUTSIDE docker
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP receiver
      - "12345:12345" # Default Alloy HTTP server / UI port
      # Expose Alloy's own metrics if scraped from HOST, otherwise optional
      - "8889:8889"  # Prometheus metrics endpoint for Alloy itself
    restart: unless-stopped
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    restart: unless-stopped
    networks:
      - observability
    depends_on:
      - loki
      - prometheus
      - tempo

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: ["-config.file=/etc/loki/local-config.yaml"] # Check this path matches the volume mount target
    ports:
      - "3100:3100" # Map to host for Grafana datasource or direct querying
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki # Changed path for clarity, ensure loki-config uses /loki
    restart: unless-stopped
    networks:
      - observability

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo/tempo-local.yaml"] # Check this path matches the volume mount target
    user: root #should find a diff way for prod environments
    volumes:
      # Ensure local file is tempo-config.yaml and it uses /tempo internal paths
      - ./tempo-config.yaml:/etc/tempo/tempo-local.yaml:ro
      - tempo-data:/data # Maps to internal /tempo path used in config
    ports:
      - "3200:3200" # Map Tempo query UI/API to host
      # - "4317:4317" # Only map OTLP gRPC if receiving from OUTSIDE docker (e.g. bypassing Alloy)
      # - "4318:4318" # Only map OTLP HTTP if receiving from OUTSIDE docker
    restart: unless-stopped
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - observability

networks:
  observability:
    driver: bridge # Default, but explicit

volumes: # Standardized syntax
  grafana-storage: {}
  loki-data: {}
  tempo-data: {}
  prometheus-data: {}