# Minimal Tempo configuration for single-node, local storage testing.

# Server configuration for the main Tempo HTTP endpoint (Grafana queries)
server:
  http_listen_port: 3200

# Distributor configuration: How Tempo receives traces
distributor:
  receivers:
    otlp:
      protocols:
        # OTLP over gRPC (Standard) - Alloy/Collectors connect here
        grpc:
          endpoint: "[::]:4317"
        # OTLP over HTTP (Alternative) - Alloy/Collectors can also connect here
        http:
          endpoint: "[::]:4318"

# Ingester configuration: Handles recent traces in memory and WAL
ingester:
  # Defaults are often sufficient for a minimal setup.
  # You might configure trace_idle_period here if needed later.
  # Lifecycler defaults to memberlist which works for single node.

# Compactor configuration: Manages block merging and retention
compactor:
  compaction:
    block_retention: 720h

# Storage configuration: Where Tempo stores trace data long-term
storage:
  trace:
    backend: local
    wal:
      path: /data/wal # Must have /wal
    local:
      path: /data/blocks # Must have /blocks

# Query Frontend configuration: Handles search requests
query_frontend:
    # Explicitly set a positive limit for concurrent search requests per tenant
    # (In single-tenant mode, this acts as the overall limit)
  max_outstanding_per_tenant: 20 # Example value, adjust as needed
  # Enable search functionality (needed for Grafana Explore)
  search:
    max_result_limit: 0

# Minimal configuration doesn't require overrides, metrics_generator etc.
# They are enabled by default or not essential for basic operation.